### ISSUE TITLE
Change (some) flatMap to compactMap?

### ISSUE THREAD

**Issue by DivineDominion** [antitypical/Result#261]
I just upgraded my code to Swift 4.1. `Optional.flatMap` is now supposed to be called `compactMap`, and similarly `Array.flatMap((T) -> U?)` is now `Array.compactMap((T) -> U?)`.

Optional and Result are very similar in nature; should we be renaming `flatMap((E) -> Result<U, Error>)` to `compactMap`, too? I don't see what was bad about flatMap because, once you got used to map/flatMap etc., it made sense.

Still, I'd vote "yes" for Swift naming consistency.

**Comment by mdiep** [comment]
> `Optional.flatMap` is now supposed to be called `compactMap`

No, `Optional.flatMap` is still `flatMap`.

> `Array.flatMap((T) -> U?)` is now `Array.compactMap((T) -> U?)`

This is because that particular `flatMap` wasn't actually a `flatMap`. `flatMap` should be `A<B> -> (B -> A<C>) -> A<C>`, while `compactMap` is `A<B> -> (B -> C?) -> A<C>`. That's why it was renamed.

`compactMap` is different because it's filtering out elements. That's another reason that it doesn't make sense for `Optional`, since that cannot go from 1 value to 0 values.

`compactMap` is a method on `Sequence` because that's where it applies.

`Result` is similar to `Optional` here. It's `flatMap` is actually `flatMap`, so it should retain that name.

**Comment by DivineDominion** [comment]
Oh, sloppy research on my part. Sorry! And thanks for taking the time to clarify.
