### ISSUE TITLE
Why internal state?

### ISSUE THREAD

**Issue by nomothetis** [antitypical/Result#35]
I've looked through the source code, since this got merged into ReactiveCocoa, and I don't understand why there is an internal state. I can't find the advantage of the extra level of nesting over simply using an enum — and neither commit that introduced the change gave a reason. Can someone explain or give a use case where this is an advantage, by any chance? Thanks!

**Comment by robrix** [comment]
[Discussion of motivation occurred in the PR](https://github.com/antitypical/Result/pull/29#issuecomment-94295741) in this case. Splitting out `State` as an internal `enum` enabled us to avoid exposing implementation details (to wit, `Box`) via the public API.

That in turn is desirable since a file importing both `Result` & any arbitrary dependency containing a public `Box` type would suffer ambiguity any time it referred `Box` directly. Since `Box` is purely an implementation detail of `Result`, this is completely avoidable.
