### ISSUE TITLE
Add a podspec (supporting watchOS, &c)

### ISSUE THREAD

**Issue by JARinteractive** [antitypical/Result#73]
please update the platforms in the pod spec to support watchOS for 0.6-beta.1

**Comment by mdiep** [comment]
Sorry, but the podspec isn't supported or maintained by this repo. It lies over [here](https://github.com/CocoaPods/Specs/blob/master/Specs/Result/0.6-beta.1/Result.podspec.json). I'd suggest opening a PR there to add watchOS. :smile:

**Comment by ikesyo** [comment]
Pull requests on the Specs repo is not recommended way now: https://github.com/CocoaPods/Specs/pull/12199. So you should contact the pod owners listed in the info by `$ pod trunk info Result`.

**Comment by Thomvis** [comment]
Like @ikesyo mentioned, since the introduction of the CocoaPods trunk, it is no longer possible to update a podspec through a PR on the Cocoapods/Specs repo.

A few weeks ago, I updated the podspec for Result by manually pulling the json from the specs repo, making changes and push it again (like @gfontenot [described](https://github.com/antitypical/Result/issues/70#issuecomment-119268580)). I'd be ok with doing this again for the requested change. We could also consider adding the .podspec to this repository, so people can update them with a PR if needed. That seems to be the approach most pods take.

@JARinteractive in the meantime, you can make a local copy of `Result.podspec` with watchOS support and use that one.

**Comment by robrix** [comment]
> We could also consider adding the .podspec to this repository, so people can update them with a PR if needed. That seems to be the approach most pods take.

In the past I’ve been reluctant to add a `.podspec` because I’m not really able to maintain them myself, and it wasn’t really necessary. I think we have a sufficient mass of invested maintainers here (whether collaborators on the repo or folks willing to fork) that it’d be worth adding one if it will make API consumers’ lives easier.

I’m still not in a great position to write one myself, but if someone would like to submit a PR with one, I’d be grateful!

Going to repurpose this issue to track that in the meantime, too.

**Comment by gfontenot** [comment]
I'm happy to maintain that, since I kind of already am. It'd be nice for it to be tracked here instead of in a random dir on my machine.

Opened a simple PR. Please make comments if I'm missing any crucial info.

**Comment by robrix** [comment]
Thanks @gfontenot :heart:
