### ISSUE TITLE
Using Result with Alamofire

### ISSUE THREAD

**Issue by kiliankoe** [antitypical/Result#77]
Hi,

I just wanted to include Result in my project and am running across a few issues. It seems to me as if Alamofire (which is already a dependency) defines its own Result type throwing problems when trying to write functions that return results. 

For example Xcode (7.0 beta 5) tells me that I can't write `Result<MyDataType, MyErrorType>` because `Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)`. I'm basing my usage of Result on [this](https://github.com/antitypical/Result/pull/62/files#diff-04c6e90faac2675aa89e2176d2eec7d8R24).

Both are linked as frameworks installed via Carthage in a Swift 2.0 project.

I'm guessing issues like this shouldn't actually be occurring, but I'm doing something wrong here. Any pointers would be great, thank you!

**Comment by neilpa** [comment]
You'll have to use the fully qualified name `Result.Result<MyDataType, MyErrorType>` to avoid the ambiguity.

**Comment by kiliankoe** [comment]
That seems logical, but Xcode doesn't interpret this correctly and is complaining.

`Reference to generic type 'Result' requires arguments in <...>`

**Comment by robrix** [comment]
This is a Swift bug:

- http://openradar.appspot.com/19774567
- http://openradar.appspot.com/20633559

**Comment by kiliankoe** [comment]
Ah, thank you. I'll be duping that then :)

I guess this issue can be closed if it'll hopefully be resolving itself soon?

**Comment by MrAlek** [comment]
I ran into the same issue. Until the radars are fixed, a work-around is to make your own struct with a type-alias in a separate file.

```
// ResultResult.swift
import Foundation
import Result

// TO-DO: As soon as https://github.com/antitypical/Result/issues/77 is resolved, this file should be removed
struct ResultResult<T, Error : ErrorType> {
    typealias t = Result<T, Error>
}
```
```
// API.swift
import Foundation
import Alamofire

typealias StringResult = ResultResult<String, NSError>.t

```

Works like a charm!

**Comment by kiliankoe** [comment]
That's a nifty workaround, thanks!

**Comment by hiragram** [comment]
@kiliankoe @MrAlek 
Is the bug of swift resolved? or still needs ResultResult?

**Comment by robrix** [comment]
Swift still has this bug.

**Comment by hiragram** [comment]
thx

**Comment by kgaidis** [comment]
Wanted to reference this workaround for people who have problems in the future:
https://github.com/Alamofire/Alamofire/issues/1271#issuecomment-224517739

```swift
import enum Result.Result
import Alamofire
```

**Comment by kgaidis** [comment]
To note, the above solution `import enum Result.Result` for some reason fails when trying to build for Release. Swift compiler had an error: `no such "decl" in module`

The `ResultResult` doesn't seem to be the most flexible either, got error in a protocol:
`Cannot specialize non-generic type JsonResult (aka 'Result<String, NSError>')`

While it might be a Swift bug, the pain is pretty real.

I'll get my workarounds, but it isn't too intuitive for anyone who is relatively new to Swift (and/or iOS). It be nice for this issue to be open, or at least clearly documented. Alamofire is one of the most popular libraries so the chance of encountering this problem is relatively high.

**Comment by NrmeenTomoum** [comment]
hbhjhkj jnjkn
